#!/usr/bin/env bash
#utilisation du while, if, elif et else
n=0
while [ $n -lt 10 ]; do
	((n++))
	if [[ $n == 4 ]]; then
		echo "bad luck"
	elif [[ $n == 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	done
