#!/usr/bin/env bash
#utilisation de while avec case
n=0
while [ $n -lt 20 ]; do
	((n++))
	case $n in 
		5)
echo "bad luck from China"
echo $n
;;
 10)
echo "bad luck from Japan"
echo $n
;;
18)
echo "bad luck from Italy"
echo $n
;;
*)
echo $n 
	;;
esac
done
