#!/usr/bin/env bash
#utilisation
n=school
if [[ -e "$n" ]];
then 
	echo "school file exists"
else
echo "school file does not exists"
fi
if  [[ -s "$n" ]];
	then
	echo "school file is emty"
else
      echo "school file is not empty"
fi
if [[ -f "$n" ]];
	then
		echo "school is a regular file"
	else
		echo "  "
fi
