#!/usr/bin/env bash
#utilisation
n=school
if [[ -e "$n" ]];
then 
	echo "school file exists"
      if  [[ -s "$n" ]];
	then
	echo "school file is not  emty"
     else
      echo "school file is empty"
fi
if [[ -f "$n" ]];
	then
		echo "school is a regular file"
fi
else
echo "school file does not exists"
fi
