#!/usr/bin/env bash
#utilisation du if et de else
if [[ -e school ]];
then 
	echo "school file exists"
      if  [[ -s school ]];
	then
	echo "school file is not emty"
     else
      echo "school file is empty"
      fi
      if [[ -f school ]];
      then
	      echo "school is a regular file"
      fi
else
	echo "school file does not exists"
fi
