#!/usr/bin/env bash
# utilisation de plusieurs commande
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$> /var/run/myscript.pid'
while :; do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"; sudo /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo /var/run/myscript.pid; exit' SIGTERM
done
